development:
  yelp_api_key: "W4mbnpD3L7EEspXf7AoUb2ArsWvdc6lKtQq5iMQ-R3qzVYWlhgya6ZZ-RVUqaD0vXKuesKJbD9aAeRKZ-R_aWXiDfPHpJjeugsrojr7BgxgIfkt2Ip07g1jVRom8ZHYx"

test:
  yelp_api_key: "W4mbnpD3L7EEspXf7AoUb2ArsWvdc6lKtQq5iMQ-R3qzVYWlhgya6ZZ-RVUqaD0vXKuesKJbD9aAeRKZ-R_aWXiDfPHpJjeugsrojr7BgxgIfkt2Ip07g1jVRom8ZHYx"

production:
  yelp_api_key: <%= ENV['YELP_API_KEY'] %>
